
services:
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: ecologistica_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: ecologistica_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: ecologistica_backend
    restart: always
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: ecologistica_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: ecologistica_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
